@HOST = http://localhost:3333

###
GET {{HOST}}

###
POST {{HOST}}/admin
Content-Type: application/json

{
    "password": "123456",
    "title": "MailShooter",
    "subtitle": "Este é um teste de email!",
    "exibitionNameFrom": "Bruno Arruda",
    "from": "bruno.arrm@gmail.com",
    "to": "bruno.arrm@gmail.com",
    "subject": "Nova API para disparo de emails!",
    "message": "Esta API está sendo utilizada para disparar emails. Teste agora!"
}

###
POST {{HOST}}/test
Content-Type: application/json

{
    "password": "654321",
    "title": "MailShooter",
    "subtitle": "Este é um teste de email!",
    "exibitionNameFrom": "Bruno Arruda",
    "from": "bruno.arrm@gmail.com",
    "to": "bruno.arrm@gmail.com",
    "subject": "Nova API para disparo de emails!",
    "message": "Esta API está sendo utilizada para disparar emails. Teste agora!"
}